name = "nav"
compatibility_date = "2024-04-29"
main = "src/index.js"
# 绑定KV命名空间
[[kv_namespaces]]
binding = "KV"
id = "8bb613c033464e5ba53be15c7dc44dc9"
#
[vars]
HOME_URL = ""
PW = ""
API_TOKEN = ""




